# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: git ftp init
            script:
              - apt-get update
              - apt-get -qq install git-ftp
              - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://192.185.176.152/api.gandulaodds.com