INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	0,	1,	'Acre'	,'AC'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	1,	1,	'Alagoas'	,'AL'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	2,	1,	'Amapá'	,'AP'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	3,	1,	'Amazonas'	,'AM'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	4,	1,	'Bahia'	,'BA'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	5,	1,	'Ceará'	,'CE'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	6,	1,	'Distrito Federal'	,'DF'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	7,	1,	'Espírito Santo'	,'ES'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	8,	1,	'Goiás'	,'GO	');
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	9,	1,	'Maranhão'	,'MA'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	10,	1,	'Mato Grosso'	,'MT'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	11,	1,	'Mato Grosso do Sul'	,'MS'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	12,	1,	'Minas Gerais'	,'MG'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	13,	1,	'Pará'	,'PA'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	14,	1,	'Paraíba'	,'PB'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	15,	1,	'Paraná	','PR'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	16,	1,	'Pernambuco'	,'PE'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	17,	1,	'Piauí'	,'PI'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	18,	1,	'Rio de Janeiro'	,'RJ'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	19,	1,	'Rio Grande do Norte'	,'RN'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	20,	1,	'Rio Grande do Sul'	,'RS'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	21,	1,	'Rondônia'	,'RO'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	22,	1,	'Roraima'	,'RR'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	23,	1,	'Santa Catarina'	,'SC'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	24,	1,	'São Paulo'	,'SP'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	25,	1,	'Sergipe'	,'SE'	);
INSERT INTO `gandulaodds`.`state` (`id`,`country_id`, `name`, `slug`) VALUES (	26,	1,	'Tocantins'	,'TO'	);