INSERT INTO `country` (`id`,`name`, `slug`) VALUES (0,'Afeganistão','AF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (1,'Africa do Sul','ZA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (2,'Albânia','AL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (3,'Alemanha','DE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (4,'Andorra','AD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (5,'Angola','AO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (6,'Anguilla','AI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (7,'Antartica','AQ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (8,'Antígua e Barbuda','AG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (9,'Antilhas Holandesas','AN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (10,'Arábia Saudita','SA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (11,'Argélia','DZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (12,'Argentina','AR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (13,'Armênia','AM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (14,'Aruba','AW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (15,'Austrália','AU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (16,'Áustria','AT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (17,'Azerbaidjão','AZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (18,'Bahamas','BS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (19,'Bangladesh','BD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (20,'Barbados','BB' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (21,'Bareine','BH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (22,'Belarus','BY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (23,'Bélgica','BE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (24,'Belize','BZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (25,'Benelux','BX' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (26,'Benin','BJ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (27,'Bermudas','BM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (28,'Bolívia','BO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (29,'Bósnia e Herzegóvina','BA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (30,'Botswana','BW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (31,'Brasil','BR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (32,'Bulgária','BG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (33,'Brunei Darussalam','BN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (34,'Burkina Faso','BF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (35,'Burundi','BI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (36,'Butão','BT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (37,'Cabo Verde','CV' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (38,'Camarões','CM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (39,'Camboja','KH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (40,'Canadá','CA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (41,'Catar','QA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (42,'Cazaquistão','KZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (43,'Chade','TD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (44,'Guiné Bissau','GW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (45,'Guine Equatorial','GQ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (46,'Haiti','HT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (47,'Holanda','NL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (48,'Honduras','HN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (49,'Hong-Kong','HK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (50,'Hungria','HU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (51,'Iêmen','YE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (52,'Ilha Bouvet','BV' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (53,'Ilha do Homem','IM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (54,'Ilha Natal','CX' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (55,'Ilha Norfalk','NF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (56,'Ilhas Cayman','KY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (57,'Ilhas Cocos','CC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (58,'Ilhas Cook','CK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (59,'Ilhas do Canal','GG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (60,'Ilhas Faroe','FO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (61,'Ilhas Heard e McDonald','HM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (62,'Ilhas Malvinas','FK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (63,'Ilhas Marianas do Norte','MP' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (64,'Ilhas Marshall','MH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (65,'Ilhas Menores','UM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (66,'Ilhas Salomão','SB' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (67,'Ilhas Turks e Caicos','TC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (68,'Ilhas Virgens (Britânicas)','VG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (69,'Ilhas Virgens (U.S.)','VI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (70,'Ilhas Wallis e Futura','WF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (71,'India','IN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (72,'Indonésia','ID' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (73,'Irã','IR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (74,'Iraque','IQ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (75,'Irlanda','IE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (76,'Islândia','IS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (77,'Israel','IL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (78,'Indonésia','ID' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (79,'Irã','IR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (80,'Iraque','IQ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (81,'Irlanda','IE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (82,'Islândia','IS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (83,'Israel','IL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (84,'Itália','IT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (85,'Jamaica','JM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (86,'Japão','JP' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (87,'Jersey','JE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (88,'Palau','PW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (89,'Panamá','PA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (90,'Papua Nova Guiné','PG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (91,'Paquistão','PK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (92,'Paraguai','PY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (93,'Peru','PE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (94,'Pitcairn','PN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (95,'Polinésia Francesa','PF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (96,'Polônia','PL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (97,'Porto Rico','PR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (98,'Portugal','PT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (99,'Quênia','KE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (100,'Quirguistão','KG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (101,'Reino Unido','GB' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (102,'República Centro Africana','CF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (103,'República da Coréia','KR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (104,'República da Macedonia','MK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (105,'República da Moldova','MD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (106,'República Dem. Do Congo','CD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (107,'República Dominicana','DO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (108,'República Pop. Dem. da Coreia','KP' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (109,'República Tcheca','CZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (110,'República Unida da Tanzânia','TZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (111,'Reunião','RE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (112,'Romênia','RO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (113,'Ruanda','RW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (114,'Saara Ocidental','EH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (115,'Saint Pierre e Miquelon','PM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (116,'Samoa Americana','AS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (117,'Samoa Ocidental','WS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (118,'Santa Helena','SH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (119,'Santa Lúcia','LC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (120,'São Marino','SM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (121,'São Vicente e Granadinas','VC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (122,'Serra Leoa','SL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (123,'Seychelles','SC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (124,'Síria','SY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (125,'Sri Lanka','LK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (126,'Sudão','SD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (127,'Chile','CL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (128,'China','CN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (129,'Chipre','CY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (130,'Colômbia','CO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (131,'Comores','KM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (132,'Congo','CG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (133,'Costa do Marfim','CI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (134,'Costa Rica','CR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (135,'Croácia','HR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (136,'Cuba','CU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (137,'Dinamarca','DK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (138,'Djibuti','DJ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (139,'Dominica','DM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (140,'Egito','EG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (141,'El Salvador','SV' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (142,'Emirados Árabes Unidos','AE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (143,'Equador','EC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (144,'Eritréia','ER' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (145,'Escritório para Harmonização no Mercado Interno','EM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (146,'Eslováquia','SK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (147,'Eslovenia','SI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (148,'Espanha','ES' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (149,'Estados Unidos da América','US' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (150,'Estônia','EE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (151,'Etiópia','ET' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (152,'Federação Russa','RU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (153,'Fiji','FJ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (154,'Filipinas','PH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (155,'Finlândia','FI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (156,'França','FR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (157,'Gabão','GA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (158,'Gambia','GM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (159,'Geórgia','GE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (160,'Gana','GH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (161,'Geórgia do Sul e Ilhas Sandwich do Sul','GS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (162,'Gibraltar','GI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (163,'Granada','GD' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (164,'Grécia','GR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (165,'Groenlândia','GL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (166,'Guadalupe','GP' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (167,'Guam','GU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (168,'Guatemala','GT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (169,'Guiana','GY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (170,'Guine','GN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (171,'Jordânia','JO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (172,'Kiribati','KI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (173,'Kuwait','KW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (174,'Laos','LA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (175,'Lesoto','LS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (176,'Letônia','LV' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (177,'Líbano','LB' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (178,'Libéria','LR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (179,'Líbia','LY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (180,'Liechtenstein','LI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (181,'Lituânia','LT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (182,'Luxemburgo','LU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (183,'Macau','MO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (184,'Madagascar','MG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (185,'Malásia','MY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (186,'Malawi','MW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (187,'Maldivas','MV' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (188,'Mali','ML' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (189,'Malta','MT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (190,'Marrocos','MA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (191,'Martinica','MQ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (192,'Maurício','MU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (193,'Mauritânia','MR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (194,'México','MX' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (195,'Mianmá','MM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (196,'Micronésia','FM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (197,'Moçambique','MZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (198,'Mônaco','MC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (199,'Mongólia','MN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (200,'Mont Serrat','MS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (201,'Montenegro','ME' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (202,'Namíbia','NA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (203,'Nauru','NR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (204,'Nepal','NP' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (205,'Nicarágua','NI' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (206,'Níger','NE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (207,'Nigéria','NG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (208,'Noruega','NO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (209,'Nova Caledônia','NC' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (210,'Nova Zelândia','NZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (211,'Omã','OM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (212,'Organização Africana de Propriedade Intelectual (OAPI)','OA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (213,'Organização Mundial de Propriedade Intelectual – OMPI (WIPO)','WO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (214,'Organização Regional de Propriedade Industrial Africana','AP' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (215,'Suécia','SE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (216,'Suíça','CH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (217,'Suriname','SR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (218,'Svalbard e Jan Mayen','SJ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (219,'Tadjiquistão','TJ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (220,'Tailândia','TH' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (221,'Taiwan','TW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (222,'Terras Austrais Francesas','TF' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (223,'Territ.Britan.Oceano Índico','IO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (224,'Território Ocupado Palestino','PS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (225,'Timor-Leste','TL' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (226,'Togo','TG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (227,'Tokelau','TK' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (228,'Tonga','TO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (229,'Trinidad e Tobago','TT' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (230,'Tunísia','TN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (231,'Turcomenistão','TM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (232,'Turquia','TR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (233,'Tuvalu','TV' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (234,'Ucrânia','UA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (235,'Uganda','UG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (236,'Uruguai','UY' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (237,'Uzbequistão','UZ' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (238,'Vanuatu','VU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (239,'Vaticano','VA' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (240,'Venezuela','VE' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (241,'Vietnã','VN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (242,'Yugoslávia','YU' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (243,'Zaire','ZR' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (244,'Zâmbia','ZM' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (245,'Zimbábue','ZW' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (246,'São Cristovão e Nevis','KN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (247,'São Tomé e Príncipe','ST' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (248,'Senegal','SN' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (249,'Sérvia','RS' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (250,'Singapura','SG' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (251,'Somália','SO' );
INSERT INTO `country` (`id`,`name`, `slug`) VALUES (252,'Suazilândia','SZ' );