INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	27	,	3	,'Dortmund','Dortmund');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	28	,	3	,'Leipzig','Leipzig');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	29	,	3	,'Mönchengladbach','Mönchengladbach');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	30	,	3	,'Munique','Munique');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	31	,	12	,'Buenos Aires','Buenos Aires');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	32	,	16	,'Salzburgo,','Salzburgo,');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	33	,	23	,'Bruges','Bruges');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	34	,	28	,'La Paz.','La Paz.');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	35	,	28	,'Santa Cruz de la Sierra','Santa Cruz de la Sierra');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	36	,	127	,'Santiago','Santiago');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	37	,	127	,'Santiago','Santiago');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	38	,	130	,'Barranquilla','Barranquilla');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	39	,	130	,'Medellín.','Medellín.');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	40	,	137	,'Hernig','Hernig');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	41	,	143	,'Quito','Quito');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	42	,	143	,'Sangolquí','Sangolquí');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	43	,	148	,'Catalunha','Catalunha');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	44	,	148	,'Madrid','Madrid');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	45	,	148	,'Sevilha','Sevilha');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	46	,	156	,'Marselha','Marselha');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	47	,	156	,'Paris','Paris');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	48	,	156	,'Rennes','Rennes');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	49	,	164	,'Pireu,','Pireu,');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	50	,	47	,'Amesterdão','Amesterdão');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	51	,	50	,'Budapeste','Budapeste');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	52	,	101	,'Liverpool','Liverpool');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	53	,	101	,'Londres','Londres');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	54	,	101	,'Manchester,','Manchester,');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	55	,	84	,'Bergamo','Bergamo');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	56	,	84	,'Formelo','Formelo');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	57	,	84	,'Milão','Milão');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	58	,	84	,'Piemonte','Piemonte');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	59	,	92	,'Assunção.','Assunção.');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	60	,	93	,'Huamanga','Huamanga');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	61	,	93	,'Trujillo','Trujillo');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	62	,	98	,'Porto','Porto');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	63	,	152	,'Moscou ','Moscou ');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	64	,	152	,'São Petersburgo','São Petersburgo');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	65	,	232	,'Istambul','Istambul');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	66	,	234	,'Donetsk','Donetsk');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	67	,	234	,'Kiev','Kiev');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	68	,	234	,'Montevidéu','Montevidéu');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	69	,	240	,'Cabudare','Cabudare');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES (	70	,	240	,'Miranda ','Miranda ');