INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 27, 2,'Artigas','Artigas');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 28, 2,'Canelones','Canelones');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 29, 2,'Melo','Cerro Largo');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 30, 2,'Colônia do Sacramento','Colônia');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 31, 2,'Durazno','Durazno');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 32, 2,'Trinidad','Flores');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 33, 2,'Florida','Florida');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 34, 2,'Minas','Lavalleja');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 35, 2,'Maldonado','Maldonado');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 36, 2,'Montevidéu','Montevidéu');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 37, 2,'Paysandú','Paysandú');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 38, 2,'Fray Bentos','Río Negro');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 39, 2,'Rivera','Rivera');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 40, 2,'Rocha','Rocha');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 41, 2,'Salto','Salto');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 42, 2,'San José de Mayo','San José');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 43, 2,'Mercedes','Soriano');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 44, 2,'Tacuarembó','Tacuarembó');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 45, 2,'Treinta y Tres','Treinta y Tres');