INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	46	,14,'	Álava	','	Vitoria-Gasteiz	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	47	,14,'	Albacete	','	Albacete	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	48	,14,'	Alicante	','	Alicante	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	49	,14,'	Almería	','	Almeria	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	50	,14,'	Astúrias	','	Oviedo	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	51	,14,'	Ávila	','	Ávila	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	52	,14,'	Badajoz	','	Badajoz	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	53	,14,'	Ilhas Baleares	','	Palma de Mallorca	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	54	,14,'	Barcelona	','	Barcelona	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	55	,14,'	Biscaia	','	Bilbao	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	56	,14,'	Burgos	','	Burgos	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	57	,14,'	Cáceres	','	Cáceres	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	58	,14,'	Cádis	','	Cádis	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	59	,14,'	Cantábria	','	Santander	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	60	,14,'	Castelló	','	Castelló de la Plana	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	61	,14,'	Ceuta	','	Ceuta	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	62	,14,'	Cidade Real	','	Ciudad Real	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	63	,14,'	Córdova	','	Córdoba	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	64	,14,'	Corunha	','	Corunha	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	65	,14,'	Cuenca	','	Cuenca	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	66	,14,'	Gerunda	','	Girona	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	67	,14,'	Granada	','	Granada	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	68	,14,'	Guadalajara	','	Guadalajara	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	69	,14,'	Guipúscoa	','	São Sebastião	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	70	,14,'	Huelva	','	Huelva	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	71	,14,'	Huesca	','	Huesca	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	72	,14,'	Jaén	','	Jaén	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	73	,14,'	La Rioja	','	Logronho	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	74	,14,'	León	','	Leão	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	75	,14,'	Lérida	','	Lérida	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	76	,14,'	Lugo	','	Lugo	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	77	,14,'	Madrid	','	Madrid	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	78	,14,'	Málaga	','	Málaga	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	79	,14,'	Melilla	','	Melilla	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	80	,14,'	Múrcia	','	Múrcia	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	81	,14,'	Navarra	','	Pamplona	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	82	,14,'	Ourense	','	Ourense	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	83	,14,'	Palência	','	Palência	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	84	,14,'	Las Palmas	','	Las Palmas de Gran Canaria	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	85	,14,'	Pontevedra	','	Pontevedra	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	86	,14,'	Salamanca	','	Salamanca	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	87	,14,'	Santa Cruz de Tenerife	','	Santa Cruz de Tenerife	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	88	,14,'	Saragoça	','	Saragoça	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	89	,14,'	Segóvia	','	Segóvia	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	90	,14,'	Sevilha	','	Sevilha	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	91	,14,'	Sória	','	Sória	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	92	,14,'	Tarragona	','	Tarragona	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	93	,14,'	Teruel	','	Teruel	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	94	,14,'	Toledo	','	Toledo	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	95	,14,'	Valência	','	Valência	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	96	,14,'	Valladolid	','	Valladolid	');
INSERT INTO `state` (`id`,`country_id`, `name`, `slug`) VALUES ( 	97	,14,'	Zamora	','	Zamora	');